export declare const preloadShaderIncludeChunks: () => void;
export declare const ScreenQuadVert: string;
export declare const SkinToTextureFrag: string;
export declare const ParticleBehavior: string;
export declare const VerticalLaserBehavior: string;
export declare const ComposerFrag: string;
export declare const GBufferVert: string;
export declare const GBufferFrag: string;
export declare const BlurPassFrag: string;
export declare const SkyboxVert: string;
export declare const SkyboxFrag: string;
