export declare const uCosT = "uCosT";
export declare const uSinT = "uSinT";
export declare const uTotalElapsedTime = "uTotalElapsedTime";
export declare const uAnimationFrame = "uAnimationFrame";
export declare const uEnabled = "uEnabled";
export declare const uNoiseTex = "uNoiseTex";
export declare const uTexelSize = "uTexelSize";
export declare const uRoughnessMap = "uRoughnessMap";
export declare const uGradientUpper = "uGradientUpper";
export declare const uGradientLower = "uGradientLower";
export declare const uBrightness = "uBrightness";
export declare const uFlickerThickness = "uFlickerThickness";
export declare const uFlickerIntensity = "uFlickerIntensity";
export declare const uFlickerFeather = "uFlickerFeather";
export declare const uFresnelScale = "uFresnelScale";
export declare const uFresnelPower = "uFresnelPower";
export declare const preloadShaderIncludeChunks: () => void;
export declare const SkyboxBaseVert: string;
export declare const SkyboxBaseFrag: string;
export declare const PBRMaterialExtendedVert: string;
export declare const PBRMaterialExtendedFrag: string;
export declare const ScreenQuadVert: string;
export declare const ScreenFrag: string;
export declare const SkinToTextureFrag: string;
export declare const TextureToInstanceVert: string;
export declare const TextureToInstanceFrag: string;
export declare const PlannarReflectionVert: string;
export declare const PlannarReflectionFrag: string;
export declare const ParticleBehavior: string;
export declare const ComposerFrag: string;
